import { Octokit } from '@octokit/rest';
import { createLLMClient } from './llm/index.js';
import type { ReviewComment, ReviewContext, ReviewResponse } from './types.js';

const promptTemplate = ({
  title,
  body,
  changedFiles,
}: {
  title: string;
  body: string | null;
  changedFiles: Array<{ path: string; patch: string | null }>;
}) => `You are a GitHub pull request reviewer. Use the pull request title, description, and file patches below to write a code review and suggest inline comments.
Return only valid JSON with keys \"review\" and \"comments\".
Comments must be an array of objects with keys \"path\", \"line\", and \"body\".
Use up to 5 comments. Do not include markdown wrappers or explanatory text outside the JSON.

PR title: ${title}

PR description: ${body ?? 'No description provided.'}

Changed files and patches:
${changedFiles
  .map(
    (file) => `File: ${file.path}\n${file.patch ? file.patch.slice(0, 1400) : 'Patch not available.'}`,
  )
  .join('\n\n')}
`;

function normalizeComment(comment: Partial<ReviewComment>): ReviewComment | null {
  if (!comment.path || typeof comment.body !== 'string') {
    return null;
  }
  const line = typeof comment.line === 'number' && comment.line > 0 ? comment.line : 1;
  return { path: comment.path, line, body: comment.body.trim() };
}

export function buildReviewPrompt(
  title: string,
  body: string | null,
  changedFiles: Array<{ path: string; patch: string | null }>,
): string {
  return promptTemplate({ title, body, changedFiles });
}

export function parseReviewResponse(text: string): ReviewResponse {
  const trimmed = text.trim();
  try {
    const parsed = JSON.parse(trimmed);
    const review = typeof parsed.review === 'string' ? parsed.review.trim() : '';
    const commentsWithNull: Array<ReviewComment | null> = Array.isArray(parsed.comments)
      ? parsed.comments.map((item: unknown) => normalizeComment(item as Partial<ReviewComment>))
      : [];
    const comments = commentsWithNull.filter((comment): comment is ReviewComment => Boolean(comment));
    return { review, comments };
  } catch {
    const first = trimmed.indexOf('{');
    const last = trimmed.lastIndexOf('}');
    if (first >= 0 && last > first) {
      return parseReviewResponse(trimmed.slice(first, last + 1));
    }
    return { review: trimmed, comments: [] };
  }
}

async function fetchPullRequestFiles(octokit: Octokit, owner: string, repo: string, pull_number: number) {
  const changedFiles: Array<{ path: string; patch: string | null }> = [];
  for await (const response of octokit.paginate.iterator(octokit.rest.pulls.listFiles, {
    owner,
    repo,
    pull_number,
    per_page: 100,
  })) {
    for (const file of response.data) {
      changedFiles.push({ path: file.filename, patch: file.patch ?? null });
    }
  }
  return changedFiles;
}

export async function runReview(context: ReviewContext): Promise<void> {
  const octokit = new Octokit({ auth: context.githubToken });
  const { data: pullRequest } = await octokit.rest.pulls.get({
    owner: context.owner,
    repo: context.repo,
    pull_number: context.pullNumber,
  });

  const changedFiles = await fetchPullRequestFiles(octokit, context.owner, context.repo, context.pullNumber);
  const prompt = buildReviewPrompt(pullRequest.title, pullRequest.body, changedFiles);
  const client = createLLMClient(context.llmProvider, {
    apiKey: context.llmApiKey,
    apiUrl: context.llmApiUrl,
    model: context.llmModel,
  });
  const response = await client.complete(prompt);
  const review = response.review || 'Automated PR review generated by Coderabbit.';
  const comments = context.reviewMode === 'summary' ? [] : response.comments.slice(0, 5);

  await octokit.rest.pulls.createReview({
    owner: context.owner,
    repo: context.repo,
    pull_number: context.pullNumber,
    commit_id: pullRequest.head.sha,
    body: review,
    event: 'COMMENT',
    comments: comments.map((comment) => ({
      path: comment.path,
      line: comment.line,
      body: comment.body,
      side: 'RIGHT',
    })),
  });
}
